# Generated by Django 4.1.7 on 2023-03-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repositories", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("name", models.CharField(max_length=4)),
                ("translation", models.JSONField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "bundle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        related_query_name="apps",
                        to="repositories.l10apps",
                        verbose_name="App bundle id",
                    ),
                ),
            ],
            options={
                "db_table": "locales",
            },
        ),
    ]
