# Generated by Django 4.1.7 on 2023-02-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locales",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
