# Generated by Django 4.1.7 on 2023-02-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("l10n_apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="L10AppTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale", models.CharField(max_length=4)),
                ("translation", models.JSONField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "bundle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apps",
                        related_query_name="apps",
                        to="l10n_apps.l10app",
                        verbose_name="App bundle id",
                    ),
                ),
            ],
        ),
    ]
